<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>SLM1 Dashboard</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 font-sans">
<h3 class="text-xl font-semibold mt-10 mb-4">Recent Reports</h3>
<div class="overflow-x-auto">
    <table class="min-w-full bg-white border border-gray-300 text-sm text-gray-800">
        <thead class="bg-gray-800 text-white">
        <tr>
            <th class="px-4 py-2">Date</th>
            <th class="px-4 py-2">Report Type</th>
            <th class="px-4 py-2">Generated By</th>
            <th class="px-4 py-2">Status</th>
        </tr>
        </thead>
        <tbody>
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">2025-05-01</td>
            <td class="px-4 py-2">Prescription Report</td>
            <td class="px-4 py-2">Admin</td>
            <td class="px-4 py-2 text-green-600">✅ Completed</td>
        </tr>
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">2025-05-02</td>
            <td class="px-4 py-2">Invoice Report</td>
            <td class="px-4 py-2">Admin</td>
            <td class="px-4 py-2 text-yellow-600">⏳ Pending</td>
        </tr>
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">2025-05-03</td>
            <td class="px-4 py-2">NSSF Data Entry</td>
            <td class="px-4 py-2">Admin</td>
            <td class="px-4 py-2 text-green-600">✅ Completed</td>
        </tr>
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">2025-05-04</td>
            <td class="px-4 py-2">Scan Document</td>
            <td class="px-4 py-2">Admin</td>
            <td class="px-4 py-2 text-green-600">✅ Completed</td>
        </tr>
        <tr class="hover:bg-gray-100">
            <td class="px-4 py-2">2025-05-05</td>
            <td class="px-4 py-2">Reports Summary</td>
            <td class="px-4 py-2">Admin</td>
            <td class="px-4 py-2 text-yellow-600">⏳ Pending</td>
        </tr>
        </tbody>
    </table>
</div>

</body>
</html>
