<?php
session_start();

if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>SLM1 Dashboard</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f8f9fa;
      font-family: "Segoe UI", sans-serif;
    }

    .sidebar {
      height: 100vh;
      background-color: #2c3e50;
      color: white;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      position: sticky;
      top: 0;
      padding-top: 20px;
    }

    .sidebar h4 {
      font-weight: bold;
      margin-bottom: 20px;
    }

    .sidebar a {
      color: #ecf0f1;
      text-decoration: none;
      padding: 12px 20px;
      display: flex;
      align-items: center;
      gap: 10px;
      transition: background 0.3s, padding-left 0.3s;
    }

    .sidebar a:hover {
      background-color: #34495e;
      padding-left: 25px;
    }

    .logout-link {
      border-top: 1px solid #7f8c8d;
      margin-top: 10px;
      padding-top: 10px;
    }

    .card {
      border-radius: 12px;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.07);
      transition: transform 0.2s;
    }

    .card:hover {
      transform: translateY(-3px);
    }

    .card h5 {
      font-size: 1.1rem;
      font-weight: 600;
    }

    .dashboard-title {
      font-weight: 700;
      color: #2c3e50;
      border-bottom: 2px solid #dee2e6;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }

    .report-table th {
      background-color: #2c3e50;
      color: white;
    }

    .report-table td, .report-table th {
      vertical-align: middle;
    }

    .report-table tbody tr:hover {
      background-color: #f1f1f1;
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 sidebar p-3">
        <div>
          <h4 class="text-center">SLM1</h4>
          <a href="admin/dashboard.php"><i class="fas fa-database"></i> Management DB</a>
          <a href="#"><i class="fas fa-chart-pie"></i> Dashboard</a>
          <a href="prescription_form.php"><i class="fas fa-prescription-bottle-alt"></i> Prescription</a>
          <a href="#"><i class="fas fa-chart-line"></i> Patient History</a>
          <a href="#"><i class="fas fa-users"></i> NSSF Data Entry</a>
          <a href="#"><i class="fas fa-camera-retro"></i> Scan Document</a>
          <a href="#"><i class="fas fa-chart-line"></i> Reports</a>
        </div>
        <div class="logout-link">
          <a href="logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
      </nav>

      <main class="col-md-10 p-4">
        <h2 class="dashboard-title">Dashboard</h2>
        <div class="row g-4">
          <div class="col-md-3">
            <div class="card p-3 text-center bg-light border-0">
              <h5><i class="fas fa-notes-medical text-primary"></i> Prescription</h5>
              <p class="fs-4 fw-bold text-primary">45</p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card p-3 text-center bg-light border-0">
              <h5><i class="fas fa-file-invoice-dollar text-success"></i> Invoice</h5>
              <p class="fs-4 fw-bold text-success">120</p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card p-3 text-center bg-light border-0">
              <h5><i class="fas fa-user-edit text-warning"></i> NSSF Entry</h5>
              <p class="fs-4 fw-bold text-warning">30</p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card p-3 text-center bg-light border-0">
              <h5><i class="fas fa-camera text-danger"></i> Scan Doc</h5>
              <p class="fs-4 fw-bold text-danger">30</p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card p-3 text-center bg-light border-0">
              <h5><i class="fas fa-chart-bar text-info"></i> Reports</h5>
              <p class="fs-4 fw-bold text-info">15</p>
            </div>
          </div>
        </div>

        <!-- Reports Table -->
        <h3 class="mt-5 mb-3">Recent Reports</h3>
        <div class="table-responsive">
          <table class="table table-bordered report-table table-striped align-middle">
            <thead>
              <tr>
                <th>Date</th>
                <th>Report Type</th>
                <th>Generated By</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr><td>2025-05-01</td><td>Prescription Report</td><td>Admin</td><td>✅ Completed</td></tr>
              <tr><td>2025-05-02</td><td>Invoice Report</td><td>Admin</td><td>⏳ Pending</td></tr>
              <tr><td>2025-05-03</td><td>NSSF Data Entry</td><td>Admin</td><td>✅ Completed</td></tr>
              <tr><td>2025-05-04</td><td>Scan Document</td><td>Admin</td><td>✅ Completed</td></tr>
              <tr><td>2025-05-05</td><td>Reports Summary</td><td>Admin</td><td>⏳ Pending</td></tr>
            </tbody>
          </table>
        </div>
      </main>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>
